
package frc.robot.commands;


import TrajectoryUtil;
import com.revrobotics.CANSparkMax.IdleMode;
import DrivetrainSubsystem.java;
import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.RobotContainer;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

/* 
String trajrctoryJSON = "paths/blue1.json";
String trajrctoryJSON = "paths/blue2.json";
String trajrctoryJSON = "paths/blue3.json";
String trajrctoryJSON = "paths/red1.json";
String trajrctoryJSON = "paths/red2.json";
String trajrctoryJSON = "paths/red3.json";

@Override

public void robotInit() {
    try {
       Path trajectoryPath = Filesystem.getDeployDirectory().toPath().resolve(trajectoryJSON);
       trajectory = TrajectoryUtil.fromPathweaverJson(trajectoryPath);
    } catch (IOException ex) {
       DriverStation.reportError("Unable to open trajectory: " + trajectoryJSON, ex.getStackTrace());
    }
 }
 

 @Override
 public class mode ();
*/

//@public class Drivetrain.Autonomus.Subsystems extends CommandBase {}

// ^this is for redefining varibles 



